# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Show time' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Show time

  target 'Show timeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Show timeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'

end
